version: '3'

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
  e2e:
    container_name: cypress
    build:
      context: .
      dockerfile: ./docker/cypress/Dockerfile
    depends_on:
      - web
    command: npm run cypress:run
    volumes:
      - ./cypress:/app/cypress
      - ./docker/cypress/cypress.json:/app/cypress.json
